//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public int AppealsID { get; set; }
        public Nullable<int> PetitionDetailsID { get; set; }
        public Nullable<int> AppealNumber { get; set; }
        public string AppealCaseNumber { get; set; }
        public string Outcome { get; set; }
    
        public virtual PetitionDetail PetitionDetail { get; set; }
    }
}
