//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coaccused
    {
        public int CoaccusedID { get; set; }
        public Nullable<int> PetitionDetailsID { get; set; }
        public string ConvictName { get; set; }
        public Nullable<int> PrisonID { get; set; }
        public Nullable<bool> Convicted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual PetitionDetail PetitionDetail { get; set; }
    }
}
