//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentPetitionReson
    {
        public int CRId { get; set; }
        public Nullable<int> PetitionDetailsID { get; set; }
        public int RId { get; set; }
        public string Explanation { get; set; }
        public string Attachment { get; set; }
    
        public virtual PetitionDetail PetitionDetail { get; set; }
        public virtual PetitionReason PetitionReason { get; set; }
    }
}
