//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyDetail
    {
        public int FamilyDetailsID { get; set; }
        public Nullable<int> ProbationAftercareID { get; set; }
        public string UserId { get; set; }
        public Nullable<int> NextOfKinID { get; set; }
        public string FamilyMemberName { get; set; }
        public string FamilyMemberIdNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string FamilyMemberOccupation { get; set; }
        public Nullable<int> FamilyMemberVitalStatusId { get; set; }
        public string FamilyMemberResidence { get; set; }
        public string FamilyMemberEconomicStatus { get; set; }
        public string Relations { get; set; }
        public Nullable<int> VisitedTimes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual NextOfKin NextOfKin { get; set; }
        public virtual ProbatioAndAftercareService ProbatioAndAftercareService { get; set; }
        public virtual VitalStatu VitalStatu { get; set; }
    }
}
