//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HearingSummary
    {
        public int HearingSummaryID { get; set; }
        public string UserId { get; set; }
        public int PetitionDetailsId { get; set; }
        public Nullable<System.DateTime> HearingDate { get; set; }
        public string RemarksOnAgeAtConviction { get; set; }
        public string RemarksOnCircumstances { get; set; }
        public string RemarksOnIfConvictFirstOffender { get; set; }
        public string RemarksOnNatureAndSeriousnessOfOffence { get; set; }
        public string RemarksOnLengthServedByConvict { get; set; }
        public string RemarksOnLengthOfPeriodServedInRemand { get; set; }
        public string PersonalCircumstancesOfOffenderAtMakingPetition { get; set; }
        public string RemarksOnInterestOfStateAndCommunity { get; set; }
        public string RemarksOnPostConvictionConductOfOffender { get; set; }
        public string RemarksOnReportsFromSDCS { get; set; }
        public string RemarksOnOtherRemediesAndOutcomes { get; set; }
        public string RemarksOnVictimRepresentation { get; set; }
        public string RemarksOnFellowInmateReport { get; set; }
        public string RemarksOnProbationServicesReports { get; set; }
        public Nullable<bool> Recommendation { get; set; }
        public string RecommendationRemarks { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PetitionDetail PetitionDetail { get; set; }
    }
}
