//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetitionerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetitionerDetail()
        {
            this.PetitionDetails = new HashSet<PetitionDetail>();
        }
    
        public int PetitionerDetailId { get; set; }
        public string UserId { get; set; }
        public string PetitionNumber { get; set; }
        public string PetitionerFirstName { get; set; }
        public string PetionerMidName { get; set; }
        public string PetitionerLastName { get; set; }
        public string PetitionerAliasName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> DateOfBirthKnown { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string IdNumber { get; set; }
        public Nullable<int> County { get; set; }
        public Nullable<int> SubCounty { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> SubLocation { get; set; }
        public string Village { get; set; }
        public Nullable<int> EthnicityId { get; set; }
        public string Ocupation { get; set; }
        public Nullable<int> LevelOfEducation { get; set; }
        public string NearestChurch { get; set; }
        public string NearestSchool { get; set; }
        public string NearestMarket { get; set; }
        public string HomeCheif { get; set; }
        public Nullable<int> NextOfKin { get; set; }
        public string NextOfKinContact { get; set; }
        public Nullable<int> NextOfKinRelation { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonPhone { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Nationality Nationality1 { get; set; }
        public virtual NextOfKin NextOfKin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetitionDetail> PetitionDetails { get; set; }
        public virtual Tribe Tribe { get; set; }
        public virtual County County1 { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual SubCounty SubCounty1 { get; set; }
        public virtual Sublocation Sublocation1 { get; set; }
    }
}
