//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrisonerHistoryInRehab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrisonerHistoryInRehab()
        {
            this.PrisonComments = new HashSet<PrisonComment>();
            this.PrisonerMedicalHistories = new HashSet<PrisonerMedicalHistory>();
            this.PrisonerTrainings = new HashSet<PrisonerTraining>();
        }
    
        public int PHId { get; set; }
        public Nullable<int> PetitionDetailsId { get; set; }
        public Nullable<int> LevelOfEductation { get; set; }
        public Nullable<int> LevelOfCurrentEducation { get; set; }
        public Nullable<bool> Training { get; set; }
        public Nullable<int> TrainingID { get; set; }
        public Nullable<bool> Deployment { get; set; }
        public Nullable<int> DeploymentID { get; set; }
        public string SocialActivities { get; set; }
        public string SpiritualGrowth { get; set; }
        public Nullable<int> ProgressiveStages { get; set; }
        public Nullable<int> CounsellingID { get; set; }
        public string physcologicalSupport { get; set; }
        public string EmotionStatus { get; set; }
        public string GeneralConduct { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Counselling Counselling { get; set; }
        public virtual Deployment Deployment1 { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual EducationLevel EducationLevel1 { get; set; }
        public virtual PetitionDetail PetitionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrisonComment> PrisonComments { get; set; }
        public virtual Training Training1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrisonerMedicalHistory> PrisonerMedicalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrisonerTraining> PrisonerTrainings { get; set; }
    }
}
