//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrisonComment
    {
        public int PCId { get; set; }
        public Nullable<int> PHId { get; set; }
        public string UserId { get; set; }
        public string PrisonComment1 { get; set; }
        public string Officer { get; set; }
        public Nullable<bool> Recommend { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual PrisonerHistoryInRehab PrisonerHistoryInRehab { get; set; }
    }
}
