//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrisonerTraining
    {
        public int PrisonerTrainingId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> PHId { get; set; }
        public Nullable<int> TrainingId { get; set; }
        public Nullable<int> TrainingLevelId { get; set; }
        public string Grade { get; set; }
        public string Attachement { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PrisonerHistoryInRehab PrisonerHistoryInRehab { get; set; }
        public virtual ProgressiveStage ProgressiveStage { get; set; }
        public virtual Training Training { get; set; }
    }
}
