//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POMACSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Victim
    {
        public int VictimId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> PetitionDetailsID { get; set; }
        public string VictimName { get; set; }
        public string County { get; set; }
        public string SubCounty { get; set; }
        public string Division { get; set; }
        public string Location { get; set; }
        public string Sublocation { get; set; }
        public string Village { get; set; }
        public string Representation { get; set; }
        public Nullable<bool> AnyReconciliation { get; set; }
        public string ReconcilliationOutcome { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PetitionDetail PetitionDetail { get; set; }
        public virtual PetitionDetail PetitionDetail1 { get; set; }
    }
}
